	<head>
    	<title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     	<meta charset="utf-8">
     	<meta name = "format-detection" content = "telephone=no" />
     	<link rel="icon" href="images/favicon.ico">
     	<link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />

        
        <script src="<?php echo BASE_URL; ?>libs/tinymce/js/tinymce/tinymce.min.js"></script>
        <script src="<?php echo BASE_URL; ?>libs/tinymce/js/tinymce/langs/es_MX.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
     
     	<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css"> 

		<style type="text/css">
			.titulo1{
			font-size:20px;
			color:#a0a2a2;
			font-weight:900;
			}

			.titulo2{
			font-size:14px;
			color:#a0a2a2;
			font-weight:900;
			}

			.form_imput{
			width:240px;
			height:32px;
			border:1px solid #cdcfd2;
			}

			.form_imput::-moz-placeholder{
			color:#777;opacity:
			}

			.form_imput:focus{
			border-color:#0B6EC7;
			-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
			box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
			}
			
		</style>
	</head>
     
    <body class="main_color" align="center">
    	<br>
    	<div class="grid_12">
            <a style="text-align:left;" title="PANEL" href="<?php echo BASE_URL; ?>panel"><img src="<?php echo BASE_URL; ?>public/img/prev.png" align="left"></a>
                
            <a style="text-align:rigth;margin-left:80%" title="BANNERS / SLIDES" href="<?php echo BASE_URL; ?>recursos/banners"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/proveedor.png" align="rigth"></a>   
        </div>  
   		<br>
   		<br>
        <br>
		<form id="form" name="form1" action="#" method="post">
        	<input type="hidden" name="guardar" value="1" />
                <?php if (isset($this->_error)): ?>
            		<div id="_error" class="alert alert-error">
	                	<a class="close" data-dismiss="alert">x</a>
	                	<?php echo $this->_error; ?>
            		</div>
        		<?php endif; ?>

        		<?php if (isset($this->_mensaje)): ?>
            		<div id="_mensaje" class="alert alert-success">
	                	<a class="close" data-dismiss="alert">x</a>
	                	<?php echo $this->_mensaje; ?>
            		</div>
        		<?php endif; ?>
        		
        		<span class="titulo1">BANNERS / SLIDES</span><br><br>
			<table cellpadding="3" cellspacing="0" width="100%" border="0" style="margin-left:10%;">        
    			<tr>
                  <td><span class="titulo2">TIPO :</span>
                  </td>
                    <td>
                        <select class="form_imput" name="tipo" id="tipo" >
                            <option value="">-Seleccione-</option>
                            <option value="1" <?php if(isset($this->datos->tipo) && ($this->datos->tipo == 1)){ ?> selected <?php } ?>>-Banner-</option>
                            <option value="2" <?php if(isset($this->datos->tipo) && ($this->datos->tipo == 2)){ ?> selected <?php } ?>>-Slide-</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><span class="titulo2">TIPO DE APERTURA :</span>
                    </td>
                    <td>
                        <select class="form_imput" name="tipo_apertura" id="tipo_apertura" >
                            <option value="">-Seleccione-</option>
                            <option value="blanck" <?php if(isset($this->datos->tipo_apertura) && ($this->datos->tipo_apertura == "blanck")){ ?> selected <?php } ?>>-Nueva Pestaña-</option>
                            <option value="else" <?php if(isset($this->datos->tipo_apertura) && ($this->datos->tipo_apertura == "else")){ ?> selected <?php } ?>>-Misma Pestaña-</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><span class="titulo2">NOMBRE:</span>
                    </td>
                    <td>
                        <input type="text" class="form_imput" id="nombre" name="nombre" value="<?php if (isset($this->datos->nombre)) echo $this->datos->nombre; ?>" />
                    </td>
                </tr>
                <tr>
                    <td><span class="titulo2">URL :</span>
                    </td>
                    <td>
                        <input type="text" class="form_imput" id="url" name="url" value="<?php if (isset($this->datos->url)) echo $this->datos->url; ?>" />
                    </td>
                </tr>
                                  
        		<tr>
                    <td colspan="2" align="center">
                        <br>
                    </td>
                </tr>                   
         </table> 
         <a href="#" class="btn" onclick="document.getElementById('form').submit()">Guardar</a>
         <br>
 </form>
 
 </body>