<?php if (isset($this->banners) && count($this->banners)) : ?>   
                    <table class="table" style="width:100%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:10%;"><b>TIPO</b></td>
                            <td style="width:20%;"><b>NOMBRE</b></td>
                            <td style="width:10%;"><b>TIPO APERTURA</b></td>
                            <td style="width:10%;"><b>ESTADO</b></td>
                            <td style="width:30%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->banners as $banners):?>
                            <tr>
                                <td><?php if($banners->tipo == 1){
                                        echo "Banner";
                                    }else{
                                        echo "Slide";
                                    }?> 
                                </td>
                                <td><?php echo $banners->nombre;?></td>
                                <td><?php echo $banners->tipo_apertura;?></td>
                                <td><?php if($banners->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>recursos/editar_banner/<?php echo $banners->id?>" class="btn2 ventanabanner"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> EDITAR</a>
                                    

                                    <?php if ($banners->archivo == "") { ?>

                                        <a href="<?php echo BASE_URL; ?>recursos/subir_foto/<?php echo $banners->id?>" class="btn3 ventanafoto"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/>SUBIR FOTO</a>

                                    <?php } 

                                    if ($banners->archivo <> ""){ ?>

                                        <a href="javascript:borrar_foto(<?php echo $banners->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> BORRAR FOTO</a>
                                        
                                    <?php } ?>
                                    
                                    <a href="<?php echo BASE_URL; ?>recursos/ver_banner/<?php echo $banners->id?>" class="btn3 ventanaver"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> VER</a>

                                    <a href="javascript:borrar_banner
                                    (<?php echo $novedad->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> ELIMINAR</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="5">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay banners o slide creados.</strong>
                </div>
            <?php endif; ?>