<!DOCTYPE html>
<html lang="en">
     <head>
     <title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css">
        
     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
	 <script src="<?php echo BASE_URL; ?>public/js/CalendarioEspanol.js" type="text/javascript"></script>
     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->


    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
      <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">


    <![endif]-->

    

<style type="text/css">
            .titulo1{
            font-size:20px;
            color:#a0a2a2;
            font-weight:900;
            }

            .titulo2{
            font-size:14px;
            color:#a0a2a2;
            font-weight:900;
            }

            .form_imput{
            width:240px;
            height:32px;
            border:1px solid #cdcfd2;
            }

            .form_imput::-moz-placeholder{
            color:#777;opacity:
            }

            .form_imput:focus{
            border-color:#0B6EC7;
            -webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
            box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
            }
            
        </style>

     </head>
     
<body class="main_color" align="center">
    <br>
    <span class="titulo1"><?php if (isset($this->banner->nombre)) echo $this->banner->nombre; ?></span><br><br>
    <table cellpadding="3" cellspacing="0" width="80%" border="0" style="margin-left:10%;">
        <tr>
            <td><?php if (file_exists("views/recursos/fotos/".$this->banner->archivo.".jpg")): ?>
             <a  href='<?php echo BASE_URL . "views/recursos/fotos/".$this->banner->archivo ?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' data-lightbox='<?php echo $this->banner->archivo?>' >
             
              <img src='<?php echo BASE_URL . "views/recursos/fotos/".$this->banner->archivo?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' style="border:1px solid #CCC;-webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);" />
              
              </a>
            <?php endif; ?></td>
        </tr>
    </table>
 </body>