<script src='https://www.google.com/recaptcha/api.js'></script>

<style>
.bare-title{
	background-color:#464d57;
	text-align:center;
	-moz-border-radius-topleft:5px;
	-webkit-border-top-left-radius:5px;
	border-top-left-radius:5px;
	-moz-border-radius-topright:5px;
	-webkit-border-top-right-radius:5px;
	border-top-right-radius:5px;
	padding-top:30px;
	padding-bottom:30px;
	clear: both;
	margin: 0 25%;
}

.bare-form{
	background-color:#FFF;
	text-align:center;
	-moz-border-radius-bottomleft:5px;
	-webkit-border-bottom-left-radius:5px;
	border-bottom-left-radius:5px;
	-moz-border-radius-bottomright:5px;
	-webkit-border-bottom-right-radius:5px;
	border-bottom-right-radius:5px;
	padding-top:15px; 
	padding-bottom:15px;
	clear: both;
	margin: 0 25%;
}

.titulo1{
	font-size:20px;
	color:#FFF;
	font-weight:900;
}
.titulo2{
	font-size:14px;
	color:#a0a2a2;
}

.form_imput{
	width:240px;
	height:32px;
	border:1px solid #cdcfd2;
}

.form_imput::-moz-placeholder{
	color:#777;opacity:
}

.form_imput:focus{
	border-color:#0B6EC7;
	-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
	box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
	}	  

.imp_email{
	background-image:url(<?php echo BASE_URL?>public/img/user.png);
	background-repeat:no-repeat;
	background-position:right;
	padding-right:34px;
	padding-left:5px;
}



  @media only screen and (min-width: 480px) and (max-width: 767px) {
	.bare-title,.bare-form{
		margin: 0 0%;
	}
  }
      @media only screen and (max-width: 767px) {
	.bare-title,.bare-form{
		margin: 0 0%;
	}
	  }

	  
</style>
<div class="content">
    <div class="container_12">
    
     <br /><br /> 
    <ul class="breadcrumb">
    <img src="<?php echo BASE_URL?>public/img/fecha_estas_en.png" style="vertical-align:middle" />
   <span class="titulobreadcrumb">Est&aacute;s en :</span>
      <li class="active">¿Olvidaste tu clave?</li>
    </ul>       
    
    
    	<div class="grid_12" style="height:80px;">&nbsp;</div>
        
            <div class="grid_5 bare-title">
                <span class="titulo1">Cooperativa Cemcop</span><br />
                <span class="titulo2">Ingresa tu correo electr&oacute;nico</span>
            </div>
            <form id="form1" name="form1" action="" method="post">  
            <div class="grid_5 bare-form">
                 <?php if (isset($this->_error)): ?>
                    <div id="_error" class="alert alert-error">
                        <a class="close" data-dismiss="alert">x</a>
                        <?php echo $this->_error; ?>
                    </div>
                  <?php endif; ?> 
				<?php if (isset($this->_mensaje)): ?>
                    <div  id="_mensaje" class="alert alert-success">
                        <a class="close" data-dismiss="alert">x</a>
                        <?php echo $this->_mensaje; ?>
                    </div>
                <?php endif; ?>  
                <br /><br />
                <input type="hidden" value="1" name="enviar" />
                <input type="text" name="email" id="email"  placeholder="Correo electr&oacute;nico" class="form_imput imp_email" />
                <br /><br />
     			<div class="grid_5" align="center">
    		 		<div class="g-recaptcha" data-sitekey="6LeE1wgTAAAAALkC81iuMKTV1jHWCf6I-QuV32-T"></div>
             	</div>
             <br /><br />
             
                <br /><br />
            <a  class="iniciarsesion" onclick="document.getElementById('form1').submit()" style="cursor:pointer">
                Recuperar Clave
            </a>
            <br /><br />
            </div> 
            </form>          
            
          </div>  
</div>
       