<section class="slider-area">
			<!-- slider start -->
			<div class="slider home2_slider">
				<div id="mainSlider" class="nivoSlider nevo-slider">
					<img src="<?php echo BASE_URL; ?>public/img/slider/slider-3.jpg" alt="main slider" title="#htmlcaption0"/>
					<img src="<?php echo BASE_URL; ?>public/img/slider/slider-1.jpg" alt="main slider" title="#htmlcaption1"/>
					<img src="<?php echo BASE_URL; ?>public/img/slider/slider-2.jpg" alt="main slider" title="#htmlcaption2"/>
				</div>	
				<div id="htmlcaption0" class="nivo-html-caption slider-caption">
					<div class="slider-progress"></div>
					<div class="slider-text">
						<div class="middle-text">
							<div class="width-cap">
								<h3 class="slider2-tiile-top home2_slider2-tiile-top top-ani-2"><span>Hand Cut and Crafted in soft Nenuine Leather</span></h3>
								<h2 class="slider2-tiile-middle home2_slider2-tiile-middle middle-ani-2"><span>Leather Bags</span></h2>
								<div class="slider2-readmore slider2-readmore_home2">
									<a href="#">explorer</a>
								</div>	
								<div class="slider2-shop slider2-shop_home2">
									<a href="#">Shopping Now</a>
								</div>								
							</div>
						</div>
					</div>					
				</div>
				<div id="htmlcaption1" class="nivo-html-caption slider-caption">
					<div class="slider-progress"></div>
					<div class="slider-text">
						<div class="middle-text">
							<div class="width-cap">
								<h3 class="slider-tiile-top top-ani-1"><span>Mad For Summer</span></h3>
								<h2 class="slider-tiile-middle middle-ani-1"><span>stripes</span></h2>
								<div class="slider-readmore">
									<a href="#">explorer</a>
								</div>
								<div class="slider-shopping">
									<a href="#">Shopping Now</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="htmlcaption2" class="nivo-html-caption slider-caption">
					<div class="slider-progress"></div>
					<div class="slider-text">
						<div class="middle-text">
							<div class="width-cap">
								<h3 class="slider2-tiile-top top-ani-2"><span>Hand Cut and Crafted in soft Nenuine Leather</span></h3>
								<h2 class="slider2-tiile-middle middle-ani-2"><span>Leather Bags</span></h2>
								<div class="slider2-readmore">
									<a href="#">explorer</a>
								</div>	
								<div class="slider2-shop">
									<a href="#">Shopping Now</a>
								</div>								
							</div>
						</div>
					</div>					
				</div>
			</div>
			<!-- slider end -->
		</section>
		<!-- slider-area end -->
		<!--start home-2 banner area -->
		<div class="home2_banner_area">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="shopping_world">
							<p>MARCAS DE NUESTRAS TIENDAS.</p>
						</div>
					</div>
				</div>
		<!--Start Branding area -->
		<div class="branding_area branding_home2">
			<div class="container">
				<div class="branding_home2_list">
					<div class="row">
						<div class="carousel_branding">
							<div class="col-lg-2">
								<?php if (isset($this->imgmarcas) && count($this->imgmarcas)) : ?>
									<?php foreach($this->imgmarcas as $imgmarcas):?>
									<div class="single_branding">
										<?php if (file_exists("views/marcas/fotos/".$imgmarcas->archivo.".jpg")): ?>
												<a href="#">
													<img src='<?php echo BASE_URL . "views/marcas/fotos/".$imgmarcas->archivo?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' alt="banner" />
												</a>
										<?php endif; ?>
									</div>
					        		<?php endforeach;?>
					        	<?php endif; ?>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand2.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand3.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand4.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand1.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand2.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand3.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href=""><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand4.jpg" alt="" /></a>
								</div>
							</div>
							<div class="col-lg-2">
								<div class="single_branding">
									<a href="#"><img src="<?php echo BASE_URL; ?>public/img/branding-image/brand1.jpg" alt="" /></a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--End Branding area -->
		<!--Start Feature area -->
		<div class="feature_area">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="feature_text">
							<h4>OFERTAS</h4>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<div class="product_list">
							<div class="single_product">
								<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/9044 espalda DSC_0060 copia.jpg" alt="" /></a>
								<div class="product_details">
									<h2>Lorem ipsum dolor</h2>
									<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
								</div>
								<div class="product_detail">
									<div class="star_icon">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
									<div class="product_button">
										<div class="cart_details">
											<a href="#" target="blank">Add to cart</a>
										</div>
										<div class="cart_details">
											<a href="#" target="expand"><i class="fa fa-expand"></i></a>
										</div>
										<div class="cart_details">
											<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
										</div>
									</div>
								</div>
								<div class="sale_product">
									<h5>Sale</h5>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<div class="product_list">
							<div class="single_product">
								<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/4.jpg" alt="" /></a>
								<div class="product_details">
									<h2>Lorem ipsum dolor</h2>
									<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
								</div>
								<div class="product_detail">
									<div class="star_icon">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
									<div class="product_button">
										<div class="cart_details">
											<a href="#" target="blank">Add to cart</a>
										</div>
										<div class="cart_details">
											<a href="#" target="expand"><i class="fa fa-expand"></i></a>
										</div>
										<div class="cart_details">
											<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<div class="product_list">
							<div class="single_product">
								<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/6_1.jpg" alt="" /></a>
								<div class="product_details">
									<h2>Lorem ipsum dolor</h2>
									<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
								</div>
								<div class="product_detail">
									<div class="star_icon">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
									<div class="product_button">
										<div class="cart_details">
											<a href="#" target="blank">Add to cart</a>
										</div>
										<div class="cart_details">
											<a href="#" target="expand"><i class="fa fa-expand"></i></a>
										</div>
										<div class="cart_details">
											<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<div class="product_list">
							<div class="single_product">
								<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/8.jpg" alt="" /></a>
								<div class="product_details">
									<h2>Lorem ipsum dolor</h2>
									<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
								</div>
								<div class="product_detail">
									<div class="star_icon">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
									</div>
									<div class="product_button">
										<div class="cart_details">
											<a href="#" target="blank">Add to cart</a>
										</div>
										<div class="cart_details">
											<a href="#" target="expand"><i class="fa fa-expand"></i></a>
										</div>
										<div class="cart_details">
											<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
										</div>
									</div>
								</div>
								<div class="sale_product">
									<h5>Sale</h5>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="product_bottom_area">
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/23.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
									<div class="sale_product">
										<h5>Sale</h5>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/24.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/10.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/11_1.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
									<div class="sale_product">
										<h5>Sale</h5>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="product_bottom_area">
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/14_3.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
									<div class="sale_product">
										<h5>Sale</h5>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/16.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/17_2_1_1.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
							<div class="product_list">
								<div class="single_product">
									<a href="product.html" target="main"><img src="<?php echo BASE_URL; ?>public/img/feature-image/11_1.jpg" alt="" /></a>
									<div class="product_details">
										<h2>Lorem ipsum dolor</h2>
										<p><span class="regular_price">$170.00</span> <span class="popular_price">$150.00</span></p>
									</div>
									<div class="product_detail">
										<div class="star_icon">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-half-o"></i>
										</div>
										<div class="product_button">
											<div class="cart_details">
												<a href="#" target="blank">Add to cart</a>
											</div>
											<div class="cart_details">
												<a href="#" target="expand"><i class="fa fa-expand"></i></a>
											</div>
											<div class="cart_details">
												<a href="#" target="heart"><i class="fa fa-heart-o"></i></a>
											</div>
										</div>
									</div>
									<div class="sale_product">
										<h5>Sale</h5>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="more_feature_area">
							<h2><a href="#">VER MAS...</a></h2>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--End Feature area -->
		<!--Start Contact info area -->
		<div class="service_info_area home2_service_info">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
						<div class="service_list">
							<h4><i class="fa fa-envelope-o"></i> info@liendobingo.com</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
						<div class="service_list">
							<h4><i class="fa fa-phone"></i> (+5555) 224 434</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
						<div class="Social_list">	
							<div class="social_icon my-class uk-scrollspy-init-inview uk-invisible">
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Like 6k" class="red-tooltip" href="#"><i class="fa fa-facebook"></i></a>
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Followers 61k" class="red-tooltip" href="#"><i class="fa fa-twitter"></i></a>
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Followers 16k" class="red-tooltip" href="#"><i class="fa fa-instagram"></i></a>
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Followers 10k" class="red-tooltip" href="#"><i class="fa fa-pinterest"></i></a>
								<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Followers 10k" class="red-tooltip" href="#"><i class="fa fa-youtube"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--End Contact info area -->
		<!--Start Blog area -->
		<div class="blog_post_area home2_blog_bt">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="feature_text">
							<h4>NOVEDADES</h4>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="carousel_blog_list">
						<?php if (isset($this->novedades) && count($this->novedades)) : ?>
							<?php foreach($this->novedades as $novedades):?>
							<div class="col-lg-3">

								<?php if (file_exists("views/novedades/fotos/".$novedades->archivo.".jpg")): ?>
										<div class="single_blog">
											<a href="<?php echo BASE_URL; ?>principal/novedad/<?php echo $novedades->id;?>">
												<img src='<?php echo BASE_URL . "views/novedades/fotos/".$novedades->archivo?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' alt="banner" />
											</a>
											<div class="blog_details">
												<a href="<?php echo BASE_URL; ?>principal/novedad/<?php echo $novedades->id;?>"><?php echo $novedades->nombre;?></a>
												<p><?php echo $novedades->tnov;?></p>
												<h3><?php echo date('d-m-Y',strtotime($novedades->fecha_creacion));?></h3>
												<a href="<?php echo BASE_URL; ?>principal/novedad/<?php echo $novedades->id;?>">
												<div class="read_more">
													<i class="fa fa-angle-right"></i>
												</div>
												</a>
											</div>
										</div>
								<?php endif; ?>
							</div>
			        		<?php endforeach;?>
			        	<?php endif; ?>
					</div>
				</div>
			</div>
		</div>