<!DOCTYPE html>
<html lang="en">
     <head>
     <title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >

     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>
     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->


    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
      <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">


    <![endif]-->
     </head>
     
     <body class="page1" id="top">
     	<div class="main_color" style="background-color:#<?php echo $this->intro->fondo;?>; height:550px;">


<?php if($this->intro->tipo == 1)://VIDEO?>

	<?php $codigo=(split('=',$this->intro->ruta));?>

<div class="container_12">
	<div class="grid_12 center" style="background-color:#<?php echo $this->intro->fondo;?>;padding-bottom:20px; padding-top:20px;">
    

<iframe width="650" height="500" src="https://www.youtube.com/embed/<?php echo $codigo[1];?>" frameborder="0" allowfullscreen></iframe>


	</div>
</div>

<?php elseif($this->intro->tipo == 2)://IMAGEN?>

<div class="container_12">
	<div class="grid_12" style="background-color:#<?php echo $this->intro->fondo;?>;padding-bottom:20px; padding-top:20px;">
<?php if (file_exists(ROOT_ADMIN . "views/intro/fotos/grande/".$this->intro->id.".jpg")): ?>
<img  src='<?php echo BASE_URL_ADMIN ."views/intro/fotos/grande/".$this->intro->id.".jpg?nocache=".date("Y-m-d H:i:s")?>' style="width:100%"/>
<?php endif; ?>
	</div>
</div>

<?php endif;?>
	</div>
</body>