<!--Start breadcrumbs area -->
    <div class="breadcrumbs-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="breadcrumb-single blog_top_area">
              <ul id="breadcrumbs">
                <li><a href=""><i class="fa fa-home"></i>Home</a></li>
                <li><span>Ι</span></li>
                <li>Quienes Somos</li>
                <li><span>Ι</span></li>
                <li>Mision</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--End breadcrumbs area -->
    <!--Start about hope area -->
    <div class="about_hope_area">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="about_hope_text">
              <h1><strong><?php echo strtoupper($this->quiensomos->nombre);?></strong></h1>
              <p><?php echo $this->quiensomos->descripcion;?></p>
              <div class="about_read_more">
                <a href="<?php echo BASE_URL; ?>principal/sciocco">Sciocco</a>

                <a href="<?php echo BASE_URL; ?>principal/vision">Vision</a>

                <a href="<?php echo BASE_URL; ?>principal/historia">historia</a>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="about_hope_image">
              <img src="<?php echo BASE_URL; ?>public/img/tienda.jpg" alt="" />
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--End about hope area -->
    <!--Start skill area -->
    <!--<div class="about_skill_area">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="about_skills">
              <h2>OUR <strong> SKILL</strong></h2>
              <p>Our skill is really high quality and standard for build your project.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <!-- single-skill-about start --> 
          <!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single-skill-about">
              <div class="progress-circular">
                  <input type="text" class="knob" value="0" data-rel="50" data-linecap="round" data-width="175" data-bgcolor="#F5F5F5" data-fgcolor="#ff343b" data-thickness=".04" data-readonly="true" disabled>
                  <h4 class="progress-h4">Marketing</h4>          
              </div>            
            </div>            
          </div>
          <!-- single-skill-about end --> 
          <!-- single-skill-about start --> 
          <!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single-skill-about">
              <div class="progress-circular">
                  <input type="text" class="knob" value="0" data-rel="65" data-linecap="round" data-width="175" data-bgcolor="#F5F5F5" data-fgcolor="#ff343b" data-thickness=".04" data-readonly="true" disabled>
                  <h4 class="progress-h4">Product Quality</h4>          
              </div>            
            </div>            
          </div>
          <!-- single-skill-about end --> 
          <!-- single-skill-about start --> 
          <!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single-skill-about">
              <div class="progress-circular">
                  <input type="text" class="knob" value="0" data-rel="85" data-linecap="round" data-width="175" data-bgcolor="#F5F5F5" data-fgcolor="#ff343b" data-thickness=".04" data-readonly="true" disabled>
                  <h4 class="progress-h4">Production Speed</h4>         
              </div>            
            </div>            
          </div>
          <!-- single-skill-about end --> 
          <!-- single-skill-about start --> 
          <!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single-skill-about">
              <div class="progress-circular">
                  <input type="text" class="knob" value="0" data-rel="90" data-linecap="round" data-width="175" data-bgcolor="#F5F5F5" data-fgcolor="#ff343b" data-thickness=".04" data-readonly="true" disabled>
                  <h4 class="progress-h4">Product Accuracy</h4>         
              </div>            
            </div>            
          </div>
          <!-- single-skill-about end --> 
        <!--</div>
      </div>
    </div>
    <!--End skill area -->
    <!--Start Creative Member area -->
    <!--<div class="creative_member_area">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="creative_member_text">
               <h2>OUR CREATIVE <strong> MEMBER</strong></h2>
               <p>Our skill is really high quality and standard for build your project.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single_creative_member">
              <div class="creative_author">
                <img src="<?php echo BASE_URL; ?>public/img/author/m14.jpg" alt="" />
              </div>
              <div class="member_info">
                <span class="member_name">Havier Macherano</span>
                <span class="member_role">Developer</span>
              </div>
              <div class="member_icons">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <svg xml:space="preserve" enable-background="new 0 0 52 52" viewBox="0 0 52 52" height="52px" width="52px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1"><path d="M51.673,0H0v51.5c0.244-5.359,3.805-10.412,7.752-13.003l36.169-23.74c4.264-2.799,7.761-8.663,7.752-14.297V0L51.673,0z"/></svg>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single_creative_member">
              <div class="creative_author">
                <img src="<?php echo BASE_URL; ?>public/img/author/m15.jpg" alt="" />
              </div>
              <div class="member_info">
                <span class="member_name">Luka Biglia</span>
                <span class="member_role">Programmer</span>
              </div>
              <div class="member_icons">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <svg xml:space="preserve" enable-background="new 0 0 52 52" viewBox="0 0 52 52" height="52px" width="52px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1"><path d="M51.673,0H0v51.5c0.244-5.359,3.805-10.412,7.752-13.003l36.169-23.74c4.264-2.799,7.761-8.663,7.752-14.297V0L51.673,0z"/></svg>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single_creative_member">
              <div class="creative_author">
                <img src="<?php echo BASE_URL; ?>public/img/author/m16.jpg" alt="" />
              </div>
              <div class="member_info">
                <span class="member_name">Anzo Perez</span>
                <span class="member_role">Designer</span>
              </div>
              <div class="member_icons">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <svg xml:space="preserve" enable-background="new 0 0 52 52" viewBox="0 0 52 52" height="52px" width="52px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1"><path d="M51.673,0H0v51.5c0.244-5.359,3.805-10.412,7.752-13.003l36.169-23.74c4.264-2.799,7.761-8.663,7.752-14.297V0L51.673,0z"/></svg>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="single_creative_member">
              <div class="creative_author">
                <img src="<?php echo BASE_URL; ?>public/img/author/m17.jpg" alt="" />
              </div>
              <div class="member_info">
                <span class="member_name">Martin Demichelis</span>
                <span class="member_role">PHP Developer</span>
              </div>
              <div class="member_icons">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <svg xml:space="preserve" enable-background="new 0 0 52 52" viewBox="0 0 52 52" height="52px" width="52px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1"><path d="M51.673,0H0v51.5c0.244-5.359,3.805-10.412,7.752-13.003l36.169-23.74c4.264-2.799,7.761-8.663,7.752-14.297V0L51.673,0z"/></svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--End Creative Member area -->
    <!--Start Branding area -->
    <div class="branding_area">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="carousel_branding">
              <div class="single_branding">
                 <?php if (isset($this->imgmarcas) && count($this->imgmarcas)) : ?>
                      <?php foreach($this->imgmarcas as $imgmarcas):?> 
                        <?php if (file_exists("views/marcas/fotos/".$imgmarcas->archivo.".jpg")): ?>
                              <img src='<?php echo BASE_URL . "views/marcas/fotos/".$imgmarcas->archivo?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' alt=""/>
                        <?php endif; ?>
                        <?php endforeach;?>
                  <?php endif; ?>
                </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand1.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand2.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand3.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand4.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand2.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand1.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand3.jpg" alt="" />
              </div>
              <div class="single_branding">
                <img src="<?php echo BASE_URL; ?>public/img/branding-image/brand2.jpg" alt="" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--End Branding area -->