
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'respuestas');
        data.addColumn('number', 'votos');
		<?php if (isset($this->respuestas) && count($this->respuestas)) : ?>
		<?php foreach ($this->respuestas as $respuesta): ?>
        data.addRows([
          ['<?php echo $respuesta->respuesta; ?>',<?php echo $respuesta->votos; ?>]
        ]);
		<?php endforeach; ?>
		<?php else: 
        echo "<strong>No hay Resultado!</strong>.";
    	 endif; ?>
	
        // Set chart option
		
        var options = {'title':'<?php if (isset($this->datos->titulo)){echo $this->datos->titulo;}?>',
                       'width':600,
                       'height':450,
					   is3D: true};

        // Instantiate and draw our chart, passing in some options..BarChart...PieChart ...ColumnChart
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>

    <?php if (isset($this->respuestas) && count($this->respuestas)) : ?>
    <div id="chart_div" align="center" ></div>
     <?php else: ?>
            <div class='alert alert-info'>
                <strong>Lo sentimos, no se ha encontrado informaci&oacute;n.</strong>
            </div>
	<?php endif; ?>
