<?php if (isset($this->red) && count($this->red)) : ?>   
    <table class="table" style="width:100%; font-size:12px;">
        <thead>
            <tr>
                <td style="width:25%;"><b>NOMBRE</b></td>
                <td style="width:50%;"><b>URL</b></td>
                <td style="width:25%;"><b>ACCIONES</b></td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->red as $red):?>
                <tr>
                    <td><?php echo $red->nombre;?></td>
                    <td><?php echo $red->url;?></td>
                    <td>
                        <a href="<?php echo BASE_URL; ?>empresa/editar_red_social/<?php echo $red->id?>" class="btn2 ventanaredes"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                        <a href="javascript:borrar_redes_sociales(<?php echo $red->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr>
                <td colspan="3">
                    <div class="clear"></div>
                    <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php else: ?>
    <div class='alert alert-info'>
        <strong>No hay redes sociales creadas.</strong>
    </div>
<?php endif; ?>