<?php if (isset($this->terminos) && count($this->terminos)) : ?>   
<table class="table" style="width:100%; font-size:12px;">
    <thead>
        <tr>
            <td style="width:25%;"><b>NOMBRE</b></td>
            <td style="width:50%;"><b>DESCRIPCIÓN</b></td>
            <td style="width:25%;"><b>ACCIONES</b></td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->terminos as $terminos):?>
            <tr>
                <td><?php echo $terminos->nombre;?></td>
                <td><?php echo $terminos->descripcion;?></td>
                <td>
                    <a href="<?php echo BASE_URL; ?>terminos/editar_termino/<?php echo $terminos->id?>" class="btn2 ventanaterminos"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                    <a href="javascript:borrar_termino(<?php echo $terminos->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                </td>
            </tr>
        <?php endforeach;?>
        <tr>
            <td colspan="3">
                <div class="clear"></div>
                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
            </td>
        </tr>
    </tbody>
</table>
<?php else: ?>
<div class='alert alert-info'>
    <strong>No hay terminos y/o condiciones creadas.</strong>
</div>
<?php endif; ?>