<?php if (isset($this->usuario) && count($this->usuario)) : ?>   
        <table class="table" style="width:100%; font-size:12px;">
        <thead>
            <tr>
                <td style="width:20%;"><b>USUARIO</b></td>
                <td style="width:15%;"><b>ROL</b></td>
                <td style="width:15%;"><b>ESTADO</b></td>
                <td style="width:40%;"><b>ACCIONES</b></td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->usuario as $usuario):?>
                <tr>
                    <td><?php echo $usuario->usuario;?></td>
                    <td><?php echo $usuario->rol;?></td>
                    <td><?php if($usuario->estado == 1){
                            echo "Activo";
                        }else{
                            echo "Inactivo";
                        }?> 
                    </td>
                    <td>
                        <a href="<?php echo BASE_URL; ?>usuarios/editar_usuario/<?php echo $usuario->id?>" class="btn2 ventanausuario"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                        
                        <a href="<?php echo BASE_URL; ?>usuarios/cambio_clave/<?php echo $usuario->id?>" class="btn3 ventanausuario"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Cambiar Clave</a>

                        <a href="javascript:borrar_usuario(<?php echo $usuario->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr>
                <td colspan="4">
                    <div class="clear"></div>
                    <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php else: ?>
    <div class='alert alert-info'>
        <strong>No hay usuarios creados.</strong>
    </div>
<?php endif; ?>