<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/form.css" />
<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
<script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>

<div class="content">
    <div class="container_12">
    
    <br /><br /> 
    <ul class="breadcrumb">
    <img src="<?php echo BASE_URL?>public/img/fecha_estas_en.png" style="vertical-align:middle" />
   <span class="titulobreadcrumb">Est&aacute;s en :</span>
      <li class="active">Mis Eventos</li>
    </ul> 
    
    	<div class="grid_12">
        <br />
            <a href="<?php echo BASE_URL; ?>micuenta/index" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mi_perfil.png" style="vertical-align:middle"/> 
            Mi Perfil
            </a> 
            
            <a href="<?php echo BASE_URL; ?>micuenta/ListadoParientes" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mis_parientes.png" style="vertical-align:middle"/> 
            Mis Parientes
            </a>

            <a href="<?php echo BASE_URL; ?>micuenta/Listadopedidos" class="btn5">
             <img src="<?php echo BASE_URL; ?>public/img/mis_pedidos.png" style="vertical-align:middle"/>
             Mis Pedidos
            </a>

            <a href="<?php echo BASE_URL; ?>micuenta/Listadoeventos" class="btn5" style="background-color:#da4f49">
            <img src="<?php echo BASE_URL; ?>public/img/mis_eventos.png" style="vertical-align:middle"/>
            Mis Eventos</a>

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoCarrito" class="btn5">
            <img src="<?php echo BASE_URL; ?>public/img/mi_carrito.png" style="vertical-align:middle"/>
            Mi Carrito</a>
        </div>

		<div class="grid_12" >
        	<div>
        		<br />
            	<font style="font-size:24px;font-weight:bold">Mis Eventos</font>
                <hr style="color:#999">
        		<br/>
        	</div>
        </div>
        
        <div class="grid_12">
        <br />
            <a href="<?php echo BASE_URL; ?>micuenta/Listadoeventos" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mi_perfil.png" style="vertical-align:middle"/> 
            Asociado
            </a> 
            
            <a href="<?php echo BASE_URL; ?>micuenta/eventosparientes" class="btn5" style="background-color:#da4f49">
            <img src="<?php echo BASE_URL; ?>public/img/mis_parientes.png" style="vertical-align:middle"/> 
            Parientes
            </a>
        </div>
        
        <div class="grid_12" >
        	<div>
        		<br />
            	<font style="font-size:18px;font-weight:bold">Parientes</font>
                <hr style="color:#999">
        		<br/>
        	</div>
            
            
            <div class="grid_12" id="lista_registros">
					<?php if (isset($this->parientes) && count($this->parientes)) : ?>
          			<?php foreach ($this->parientes as $pariente): ?>
                    <div class="grid_12" style="margin-bottom:10px;background-color:#FFF;border:#E8E8E8 1px solid;padding-left:5px;">
   					   	<div class="grid_2" style="width:140px; height:115px; background-color:#FFF;">
             				<?php if (file_exists(ROOT_ADMIN."views/cursos/fotos/$pariente->id.jpg")):?>       
        						<a href="<?php echo BASE_URL . "cursos/DetalleCurso/$pariente->id"?>"><img src="<?php echo BASE_URL_ADMIN . "views/cursos/fotos/".$pariente->id.".jpg?nocache=".date("Y-m-d H:i:s").""?>" alt="" width="110" height="110" /></a>
           					<?php else:?>
        						<a><img src="<?php echo BASE_URL . "public/img/imagen_no_disponible_123.png?nocache=".date("Y-m-d H:i:s").""?>" alt="" width="110" height="110" /></a>
        					<? endif;?>
                        </div>
                        <div class="grid_2" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">	
							<b>Pariente:</b> <?php echo $pariente->nombres." ".$pariente->apellidos; ?>
                        </div>
                        <div class="grid_2" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">	
							<b>Evento:</b> <?php echo substr($pariente->nombre,0,40); ?>
                        </div>
                        <div class="grid_2" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                           	<b>Fecha Inicio</b>: <?php echo date('Y-m-d' , strtotime($pariente->fecha_iniciacion)); ?>
                        </div>
                        <div class="grid_2" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                           	<b>Fecha Fin:</b> <?php echo date('Y-m-d' , strtotime($pariente->fecha_finalizacion)); ?></font>
                        </div>
                        <div class="grid_1" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                           	<b>Tipo:</b> <?php if($pariente->tipo ==1){
								echo "Curso";
							}else if ($pariente->tipo == 2){
								echo "Capacitacion";
							}else if ($pariente->tipo ==3){
								echo "Evento";
							}?></font>
                        </div>
                        <div class="grid_1">
                           	<a href="#" class="btn5 delete" onClick="javascript:borrar_eventofamilia(<?php echo trim($pariente->inscripcion)?>)" style="background-color:#da4f49;"><img src="<?php echo BASE_URL; ?>public/img/eliminar.png" style="vertical-align:middle"/> Eliminar</a>
                        </div>
					</div>
					<?php endforeach;?>
                    <div class="clear"></div>
					<?php if (isset($this->paginacion)) echo $this->paginacion; ?>
					<?php else: ?>
                    	<div class='alert alert-info'>
                           	<strong>No hay eventos para los parientes.</strong>
                        </div>
					<?php endif; ?>
                </div>  
            
            
            
        </div>

    </div>
</div>        