
<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/form.css" />
<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
<script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>

<script type="text/javascript">
$(document).ready(function() {

    $(".realizarpedido").fancybox({
        'showCloseButton': false,
        'width': 450,
        'height': 650,
        'autoSize': false,
        'autoDimensions': false,
        'transitionIn': 'none',
        'transitionOut': 'none',
        'type': 'iframe',
        'beforeClose': function() {
            window.location.reload();
        }

    });
	
	$(".editar").fancybox({
        'showCloseButton': false,
        'width': 300,
        'height': 460,
        'autoSize': false,
        'autoDimensions': false,
        'transitionIn': 'none',
        'transitionOut': 'none',
        'type': 'iframe',
        'beforeClose': function() {
            window.location.reload();
        }

    });
});
</script>

<div class="content">
    <div class="container_12">
    
     <br /><br /> 
    <ul class="breadcrumb">
    <img src="<?php echo BASE_URL?>public/img/fecha_estas_en.png" style="vertical-align:middle" />
   <span class="titulobreadcrumb">Est&aacute;s en :</span>
   <li>Mi Cuenta <span class="divider">/</span></li>
      <li class="active">Mi Carrito</li>
    </ul>    
        
    	<div class="grid_12">
        <br />
            <a href="<?php echo BASE_URL; ?>micuenta/index" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mi_perfil.png" style="vertical-align:middle"/> 
            Mi Perfil
            </a> 

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoParientes" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mis_parientes.png" style="vertical-align:middle"/> 
            Mis Parientes
            </a> 
            
            <a href="<?php echo BASE_URL; ?>micuenta/Listadoeventos" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mis_eventos.png" style="vertical-align:middle"/>
            Mis Eventos</a>
            
            <span>
            	<img src="<?php echo BASE_URL; ?>public/img/vertical.png" />
            </span>
            
            <a href="<?php echo BASE_URL; ?>micuenta/Listadopedidos" class="btn5" >
             <img src="<?php echo BASE_URL; ?>public/img/mis_pedidos.png" style="vertical-align:middle"/>
             Mis Pedidos
            </a>

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoCarrito" class="btn5" style="background-color:#da4f49">
            <img src="<?php echo BASE_URL; ?>public/img/mi_carrito.png" style="vertical-align:middle"/>
            Mi Carrito
            </a>
        </div>

		<div class="grid_12" >
        <?php $canttotal=0; $totalfinal=0;
         if (isset($this->totales) && count($this->totales)) : 
         $canttotal=$this->totales->cant; $totalfinal=$this->totales->subto;
         endif; ?>
        	<div>
        		<br />
            	<font style="font-size:24px;font-weight:bold">Mi Carrito</font>
                <hr style="color:#999" />
        		<font style="font-size:16px;font-weight:bold;color:#F00">Importante: </font><font>Los productos que se encuentran en el carro de compras no se reservan hasta que finalice la compra.</font>    
        	</div>
            <br />
            <div class="container_12">
        		<div class="grid_12" id="lista_registros">
					<?php if (isset($this->Micarrito) && count($this->Micarrito)) : ?>
          			<?php foreach ($this->Micarrito as $carrito): ?>
                    <div class="grid_12" style="margin-bottom:10px;background-color:#FFF;border:#E8E8E8 1px solid;padding-left:5px;">
   					   	<div class="grid_2" style="width:140px; height:115px; background-color:#FFF;">
             				<?php if (file_exists(ROOT_ADMIN."views/producto/fotos/$carrito->archivo.jpg")):?>       
        						<img src="<?php echo BASE_URL_ADMIN . "views/producto/fotos/".$carrito->archivo.".jpg?nocache=".date("Y-m-d H:i:s").""?>" alt="" width="110" height="110" />
           					<?php else:?>
        						<img src="<?php echo BASE_URL . "public/img/imagen_no_disponible_123.png?nocache=".date("Y-m-d H:i:s").""?>" alt="" width="110" height="110" />
        					<? endif;?>
                        </div>
                        <div class="grid_4" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">	
							<b>Producto:</b> <?php echo substr($carrito->producto,0,40); ?>
                        </div>
                        <div class="grid_2" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                           	<b>Cantidad</b>: <?php echo $carrito->cantidad; ?>
                        </div>
                        <div class="grid_1" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                           	<b>Precio Unitario:</b> $<?php echo number_format($carrito->precio,0,",","."); ?></font>
                        </div>
                        <div class="grid_1" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                           	<b>Precio Total:</b> $<?php echo number_format($carrito->subtotal,0,",","."); ?></font>
                        </div>
                        <div class="grid_2">
                        	<a href="<?php echo BASE_URL; ?>micuenta/EditarDetalle/<?php echo trim($carrito->id) ?>" class="btn5 editar" ><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                           	<a href="#" class="btn5 delete" onClick="javascript:borrar_detalle_carrito(<?php echo trim($carrito->id)?>)" style="background-color:#da4f49;"><img src="<?php echo BASE_URL; ?>public/img/eliminar.png" style="vertical-align:middle"/> Eliminar</a>
                        </div>
                        
					</div>
					<?php endforeach;?>
                    <div class="clear"></div>
                    
			<?php if (isset($this->Micarrito) && count($this->Micarrito)) : ?>
            <div class="container_12">
                <div class="grid_6" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                <b>Cantidad Total de Productos:</b> <?php echo number_format($canttotal,0,",","."); ?></font>	
                </div>
                <div class="grid_6" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
                <b>Valor Total en Carrito:</b> $<?php echo number_format($totalfinal,0,",","."); ?></font>	
                </div>
            </div>
            <?php endif; ?>                    
                    
					<?php if (isset($this->paginacion)) echo $this->paginacion; ?>
					<?php else: ?>
                    	<div class='alert alert-info'>
                           	<strong>No hay productos en tu carrito.</strong>
                        </div>
					<?php endif; ?>
                </div>  
        	</div>
            
            
            
            <div class="grid_12">
            	<div class="grid_3">
                	<?php if (isset($this->Micarrito) && count($this->Micarrito)) : ?>
            		<div >
                		<div class="clear"></div>
                		<div class="btns" ><a href="<?php echo BASE_URL; ?>micuenta/BorrarListadoCarrito" class="btn5" onclick="document.getElementById('form').submit()" style="background-color:#da4f49;"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Borrar Todos</a></div> 
                	</div>
                    <?php endif; ?>
                </div>
            	<div class="grid_3">
            		<div >
                		<div class="clear"></div>
                		<div class="btns"><a href="<?php echo BASE_URL; ?>compras" class="btn5" onclick="document.getElementById('form').submit()"><img src="<?php echo BASE_URL; ?>public/img/seguir_comprando.png" style="vertical-align:middle"/> Comprar más</a></div> 
                	</div>
                </div>
                <div class="grid_3">
                	<?php if (isset($this->Micarrito) && count($this->Micarrito)) : ?>
            		<div >
                		<div class="clear"></div>
                		<div class="btns"><a href="<?php echo BASE_URL; ?>micuenta/RealizarPedido" class="btn5 realizarpedido" onclick="document.getElementById('form').submit()"><img src="<?php echo BASE_URL; ?>public/img/finalizar_compra.png" style="vertical-align:middle"/> Finalizar Compra</a></div>
                	</div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>        