<style type="text/css">
.form_imput{
	width:340px;
	height:32px;
	border:1px solid #cdcfd2;
	margin-bottom:5px;
}

.form_imput::-moz-placeholder{
	color:#777;opacity:
}

.form_imput:focus{
	border-color:#0B6EC7;
	-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
	box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
	}
</style>
<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
<script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>

<script type="text/javascript">
$(document).ready(function() {

    $(".ventanafoto").fancybox({
        'showCloseButton': false,
        'width': 650,
        'height': 370,
        'autoSize': false,
        'autoDimensions': false,
        'transitionIn': 'none',
        'transitionOut': 'none',
        'type': 'iframe',
        'beforeClose': function() {
            window.location.reload();
        }

    });
});
</script>
<div class="content">
    <div class="container_12">
    
     <br /><br /> 
    <ul class="breadcrumb">
    <img src="<?php echo BASE_URL?>public/img/fecha_estas_en.png" style="vertical-align:middle" />
   <span class="titulobreadcrumb">Est&aacute;s en :</span>
      <li>Mi Cuenta <span class="divider">/</span></li>
      <li class="active">Mi Perfil</li>
    </ul>         
    
    	<div class="grid_12">
        <br />

            <a href="<?php echo BASE_URL; ?>micuenta/index" class="btn5" style="background-color:#da4f49">
            <img src="<?php echo BASE_URL; ?>public/img/mi_perfil.png" style="vertical-align:middle"/> 
            Mi Perfil
            </a> 

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoParientes" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mis_parientes.png" style="vertical-align:middle"/> 
            Mis Parientes
            </a> 
            
            <a href="<?php echo BASE_URL; ?>micuenta/Listadoeventos" class="btn5">
            <img src="<?php echo BASE_URL; ?>public/img/mis_eventos.png" style="vertical-align:middle"/>
            Mis Eventos</a>
            
            <span>
            	<img src="<?php echo BASE_URL; ?>public/img/vertical.png" />
            </span>
            
            <a href="<?php echo BASE_URL; ?>micuenta/Listadopedidos" class="btn5">
             <img src="<?php echo BASE_URL; ?>public/img/mis_pedidos.png" style="vertical-align:middle"/>
             Mis Pedidos
            </a>

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoCarrito" class="btn5">
            <img src="<?php echo BASE_URL; ?>public/img/mi_carrito.png" style="vertical-align:middle"/>
            Mi Carrito
            </a>
                        
        </div>
        
         <br /><br />   
        <div class="grid_12" >
        	<div>
        		<br />
            	<font style="font-size:24px;font-weight:bold">Mi Perfil</font>
                <hr style="color:#999" />
        		<br/>
        	</div>
        </div> 
        
        <div class="grid_6">
<table class="table" style="width:100%; font-size:12px;">
    <tbody>
        <tr>
            <td style="font-weight:bold" width="30%">Tipo de documento:</td>
            <td><?php echo $this->infoperfil->tipo_documento; ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">N&uacute;mero de Documento:</td>
            <td><?php echo $this->infoperfil->num_docu; ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">Nombre:</td>
            <td><?php echo $this->infoperfil->nombre; ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">Genero:</td>
            <td>
			<?php if($this->infoperfil->genero == 1):
				echo "Femenino";
			else:
				echo "Masculino";
			endif;	
			 ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">Tel&eacute;fono:</td>
            <td><?php echo $this->infoperfil->telefono; ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">Celular:</td>
            <td><?php echo $this->infoperfil->celular; ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">Direcci&oacute;n:</td>
            <td><?php echo $this->infoperfil->direccion; ?></td>
        </tr> 
        <tr>
            <td style="font-weight:bold">Ciudad:</td>
            <td><?php echo $this->infoperfil->ciudadnombre; ?></td>
        </tr>         
        
         <tr>
            <td style="font-weight:bold">Empresa:</td>
            <td><?php echo $this->infoperfil->empresa; ?></td>
        </tr>        
         <tr>
            <td style="font-weight:bold">Cargo:</td>
            <td><?php echo $this->infoperfil->cargo; ?></td>
        </tr>        
         <tr>
            <td style="font-weight:bold">Correo electr&oacute;nico:</td>
            <td><?php echo $this->infoperfil->email; ?></td>
        </tr>        
         <tr>
            <td style="font-weight:bold">Centro de costos:</td>
            <td><?php echo $this->infoperfil->centro_costos; ?></td>
        </tr>
                                                    
    </tbody>
</table>
		</div>
        
        
        <div class="grid_6" align="center">
        <div class="grid_6" align="left" style="padding-left:73px;">
        <b>Tu Foto:</b>
        </div>    
			 <?php if (file_exists(ROOT_ADMIN . "views/afiliados/fotos/".$this->infoperfil->id.".jpg")): ?>
             <a  href='<?php echo BASE_URL_ADMIN . "views/afiliados/fotos/grande/".$this->infoperfil->id ?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' data-lightbox='<?php echo $this->infoperfil->id?>' >
             
              <img src='<?php echo BASE_URL_ADMIN . "views/afiliados/fotos/".$this->infoperfil->id?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' style="border:1px solid #CCC;-webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);" />
              
              </a>
            <?php else: ?>
            
                <img src='<?php echo BASE_URL; ?>public/img/img_nodis_micuenta' style="border:1px solid #CCC;-webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);"/>
                
            <?php endif; ?>
            <br /><br />
            <a  href="<?php echo BASE_URL.'micuenta/subirFoto'; ?>" class="btn ventanafoto">
            <img src="<?php echo BASE_URL; ?>public/img/cambiar_foto.png" style="vertical-align:middle"/>
                Cambiar Foto
            </a>
            <?php if (file_exists(ROOT_ADMIN . "views/afiliados/fotos/".$this->infoperfil->id.".jpg")): ?>
            <a onclick="javascript:borrar_foto()" class="btn" style="cursor:pointer">
            <img src="<?php echo BASE_URL; ?>public/img/eliminar_foto.png" style="vertical-align:middle"/>
                Eliminar  Foto
            </a>
            <?php endif; ?>
        </div>
        
        <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

        <div class="grid_6" align="center">
        <div class="grid_6" align="left" style="padding-left:53px;">
        <b>Cambiar la contrase&ntilde;a:</b>

        </div>
        <div class="grid_6" align="center">
           <?php if (isset($this->_error)): ?>
                <div  id="_error" class="alert alert-danger" align="left">
                    <a class="close" data-dismiss="alert">x</a>
                    <?php echo $this->_error; ?>
                </div>
            <?php endif; ?>
            <?php if (isset($this->_mensaje)): ?>
                <div  id="_mensaje" class="alert alert-success" align="left">
                    <a class="close" data-dismiss="alert">x</a>
                    <?php echo $this->_mensaje; ?>
                </div>
            <?php endif; ?>
        </div>    
        <form id="form" name="form" method="post">
           <input type="hidden" name="guardar" id="guardar" value="1" />
           
          	<input type="password" name="contrasenaactual" id="contrasenaactual" placeholder="Contraseña Actual" value="" class="form_imput" />
              <input type="password" name="contrasena" id="contrasena" placeholder="Nueva Contraseña" value="" class="form_imput" />
              
              <input type="password" name="repitecontrasena" id="repitecontrasena" placeholder="Repetir Contraseña" value="" class="form_imput"/>
              
              <div class="btns">
              <a href="#" class="btn" onclick="document.getElementById('form').submit()">
              <img src="<?php echo BASE_URL; ?>public/img/guardar.png" style="vertical-align:middle"/>
              Cambiar
              </a>
              </div>
        </form>      
        </div>
    </div>
</div>        