<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/form.css" />

<style>
.blue { color: #185875; }
.yellow { color: #FFF842; }

.tablanueva th h1 {
	font-weight: bold;
	font-size: 13PX;
  text-align: left;
  color: #999;
}

.tablanueva td {
	  font-weight: normal;
	  font-size: 13PX;
  -webkit-box-shadow: 0 2px 2px -2px #0E1119;
	   -moz-box-shadow: 0 2px 2px -2px #0E1119;
	        box-shadow: 0 2px 2px -2px #0E1119;
}

.tablanueva {
	  text-align: left;
	  overflow: hidden;
	  width: 100%;
	  margin: 0 auto;
  display: table;
  padding: 0 0 8em 0;
}

.tablanueva td, .tablanueva th {
	  padding-bottom: 1%;
	  padding-top: 1%;
  padding-left:2%;  
}

/* Background-color of the odd rows */
.tablanueva tr:nth-child(odd) {
	  background-color: #ffffff;
}

/* Background-color of the even rows */
.tablanueva tr:nth-child(even) {
	  background-color: #ffffff;
}

.tablanueva th {
	  background-color: #ffffff;
}

.tablanueva td:first-child { color: #FB667A; }

.tablanueva tr:hover {
   background-color: #CCCCCC;
-webkit-box-shadow: 0 6px 6px -6px #0E1119;
	   -moz-box-shadow: 0 6px 6px -6px #0E1119;
	        box-shadow: 0 6px 6px -6px #0E1119;
}

@media (max-width: 800px) {
.tablanueva td:nth-child(2),
.tablanueva th:nth-child(2) { display: none; }
}

</style>

<div class="content">
    <div class="container_12">
    
     <br /><br /> 
    <ul class="breadcrumb">
    <img src="<?php echo BASE_URL?>public/img/fecha_estas_en.png" style="vertical-align:middle" />
   <span class="titulobreadcrumb">Est&aacute;s en :</span>
   <li>Mi Cuenta <span class="divider">/</span></li>
      <li class="active">Mis Pedidos</li>
    </ul>    
        
    	<div class="grid_12">
        <br />
            <a href="<?php echo BASE_URL; ?>micuenta/index" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mi_perfil.png" style="vertical-align:middle"/> 
            Mi Perfil
            </a> 

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoParientes" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mis_parientes.png" style="vertical-align:middle"/> 
            Mis Parientes
            </a> 
            
            <a href="<?php echo BASE_URL; ?>micuenta/Listadoeventos" class="btn5" >
            <img src="<?php echo BASE_URL; ?>public/img/mis_eventos.png" style="vertical-align:middle"/>
            Mis Eventos</a>
            
            <span>
            	<img src="<?php echo BASE_URL; ?>public/img/vertical.png" />
            </span>
                        
            <a href="<?php echo BASE_URL; ?>micuenta/Listadopedidos" class="btn5" style="background-color:#da4f49">
             <img src="<?php echo BASE_URL; ?>public/img/mis_pedidos.png" style="vertical-align:middle"/>
             Mis Pedidos
            </a>

            <a href="<?php echo BASE_URL; ?>micuenta/ListadoCarrito" class="btn5">
            <img src="<?php echo BASE_URL; ?>public/img/mi_carrito.png" style="vertical-align:middle"/>
            Mi Carrito
            </a>
        </div>

		<div class="grid_12" >
        	<div>
        		<br />
            	<font style="font-size:24px;font-weight:bold">Mis Pedidos</font>
                <hr style="color:#999" />
        		<br/>
        	</div>
            <br />
            <div class="grid_12">
        		<div id="lista_registros" class="grid_12">
					<?php if (isset($this->pedidos) && count($this->pedidos)) : ?>
          			<table class="tablanueva">
                    	<thead>
                        	<tr>
                            	<th><h1>Nro Pedido</h1></th>
                                <th><h1>Fecha</h1></th>
                                <th><h1>Estado</h1></th>
                                <th><h1>Valor</h1></th>
                                <th><h1>&nbsp;</h1></th>
                            </tr>
                        </thead>
					
					<?php foreach ($this->pedidos as $pedido): ?>
                    	<tbody>
                        	<tr>
                            	<td><?php echo $pedido->nro_pedido;?></td>
                                <td><?php echo $pedido->fecha_pedido;?></td>
                                <td><?php if($pedido->estado == 1){?> Solicitado <?php }else{?>	Despachado <?php }?></td>
                                <td><?php echo number_format($pedido->valor_total,0,",",".");?></td>
                                <td><a href='<?php echo BASE_URL . 'micuenta/ver_pedido/' . $pedido->id; ?>' onclick="window.open(this.href, 'mywin' , 'left=20,top=20,width=910,height=500,toolbar=1,resizable=0'); return false;" class="btn5 editar" ><img src="<?php echo BASE_URL; ?>public/img/pedido.png" style="vertical-align:middle"/> Ver</a></td>
                            </tr>
						</tbody>                                      
          			<?php endforeach;?>
                    </table>
                    <div class="clear"></div>
					<?php if (isset($this->paginacion)) echo $this->paginacion; ?>
					<?php else: ?>
                    	<div class='alert alert-info'>
                           	<strong>No se han Pedidos.</strong>
                        </div>
					<?php endif; ?>
                </div>  
        	</div>
        </div>
    </div>
</div>        