<!DOCTYPE html>
<html lang="en">
     <head>
     <title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css">
        
     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>


    <script src="<?php echo BASE_URL; ?>public/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>

    <script src="<?php echo BASE_URL; ?>public/js/CalendarioEspanol.js" type="text/javascript"></script>

     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->


    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
      <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">


    <![endif]-->

    

<style type="text/css">
.form_imput{
	width:210px;
	height:28px;
	border:1px solid #cdcfd2;
	margin-bottom:5px;
}

.form_imput::-moz-placeholder{
	color:#777;opacity:
}

.form_imput:focus{
	border-color:#0B6EC7;
	-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
	box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
	}
</style>
<script type="text/javascript">
$(document).ready(function() {
    $('#fecha_nacimiento').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd',
        yearRange: '-100:+0'

    });
});
</script>
     </head>
     
     <body class="main_color">

      <div id="zonaerror" class="alert alert-danger" style="display:none">
      </div>
      <div id="zonaexito" class="alert alert-success" style="display:none">
      </div>     

    <ul class="breadcrumb">
    <img src="<?php echo BASE_URL?>public/img/fecha_estas_en.png" style="vertical-align:middle" />
   <span class="titulobreadcrumb">Est&aacute;s en :</span>
      <li>Mis parientes<span class="divider">/</span></li>
      <li class="active">Crear pariente</li>
    </ul>    
    
<form id="form" name="form1" action="#" method="post">
        <input type="hidden" name="guardar" value="1" />
                <?php if (isset($this->_error)): ?>
            <div id="_error" class="alert alert-error">
                <a class="close" data-dismiss="alert">x</a>
                <?php echo $this->_error; ?>
            </div>
        <?php endif; ?>

        <?php if (isset($this->_mensaje)): ?>
            <div id="_mensaje" class="alert alert-success">
                <a class="close" data-dismiss="alert">x</a>
                <?php echo $this->_mensaje; ?>
            </div>
        <?php endif; ?>
		<table cellpadding="3" cellspacing="0" width="100%" border="0" class="table">
            <tr>
                <td colspan="2" style="padding-bottom:30px;">los campos con asterisco(<span style="color:#F00; font-weight:bold">*</span>) son obligatorios.</td>
            </tr>
        		<tr>
                <td width="40%"><strong>Tipo de Documento:</strong><span style="color:#F00; font-weight:bold">*</span></td>
                    <td>
                        <select class="form_imput" name="tipo_documento" id="tipo_documento" >
                            <option value="">-Seleccione-</option>
                            <?php foreach ($this->tipo_documento as $tipo_docu): ?>
                                    <option value="<?php echo $tipo_docu->id; ?>" <?php if (isset($this->datos->tipo_documento) and ($this->datos->tipo_documento == $tipo_docu->id)): ?> selected='selected' <?php endif; ?>><?php echo $tipo_docu->tipo_documento; ?></option>
        
                            <?php endforeach; ?>
                        </select>
                    </td>
            </tr>            
        			<tr>
               		<td><strong>N&uacute;mero de Documento:</strong><span style="color:#F00; font-weight:bold">*</span></td>
                        <td>
                        <input type="text" class="form_imput" id="num_docu" name="num_docu" value="<?php if (isset($this->datos->num_docu)) echo $this->datos->num_docu; ?>" />
                        </td>
                </tr>
                    	<tr>
                        <td>
                        <strong>Nombres:</strong><span style="color:#F00; font-weight:bold">*</span>
                        </td>
                            <td>
                            <input type="text" class="form_imput" id="nombres" name="nombres" value="<?php if (isset($this->datos->nombres)) echo $this->datos->nombres; ?>" />
                            </td>
                    </tr>
                        	<tr>
                            <td>
                            <strong>Apellidos:</strong>
                            </td>
                                <td>
                                <input type="text" class="form_imput" id="apellidos" name="apellidos" value="<?php if (isset($this->datos->apellidos)) echo $this->datos->apellidos; ?>" />
                                </td>
                        </tr>
                            	<tr>
                                <td>
                                <strong>G&eacute;nero:</strong>
                                </td>
                                    <td>
                            <select class="form_imput" name="genero" id="genero" >
                                <option value="">-Seleccione-</option>
                                        <option value="1" <?php if (isset($this->datos->genero) and ($this->datos->genero == 1)): ?> selected='selected' <?php endif; ?>>Femenino</option>
                                        <option value="2" <?php if (isset($this->datos->genero) and ($this->datos->genero == 2)): ?> selected='selected' <?php endif; ?>>Masculino</option>
                            </select>
                                    </td>
                            </tr>
                            		<tr>
                                 	<td><strong>Fecha de nacimiento:</strong></td>
                                    <td>
                                    <input type="text" class="form_imput" id="fecha_nacimiento" name="fecha_nacimiento" value="<?php if (isset($this->datos->fecha_nacimiento)) echo $this->datos->fecha_nacimiento; ?>" />
                                    </td>  
                               </tr>                          
                                    	<tr>
                                        <td ><strong>Parentesco:</strong><span style="color:#F00; font-weight:bold">*</span></td>
                                            <td>
                                                <select class="form_imput" name="parentesco" id="parentesco" >
                                                    <option value="">-Seleccione-</option>
                                                    <?php foreach ($this->parentescos as $parentesco): ?>
                                                            <option value="<?php echo $parentesco->id; ?>" <?php if (isset($this->datos->parentesco) and ($this->datos->parentesco == $parentesco->id)): ?> selected='selected' <?php endif; ?>><?php echo $parentesco->parentesco; ?></option>
                                
                                                    <?php endforeach; ?>
                                                </select>
                                            </td>
                                    </tr>  
                                    		<tr>
                                        <td colspan="2" align="right">
                                            <a href="#" class="btn" onclick="document.getElementById('form').submit()">Guardar</a>
                                        </td>
                                    </tr>                   
         </table> 
 </form>
 
 </body>