<?php if (isset($this->misparientes) && count($this->misparientes)) : ?>   
	<table class="table" style="width:100%; font-size:12px;">
    <thead>
        <tr>
            <td><b>NUMERO DE IDENTIFICACI&Oacute;N</b></td>
            <td><b>NOMBRE</b></td>
            <td><b>PARENTESCO</b></td>
            <td><b>ACCIONES</b></td>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->misparientes as $misparientes):?>
        <tr>
            <td><?php echo $misparientes->nro_documento;?></td>
            <td><?php echo $misparientes->nombres;?></td>
            <td><?php echo $misparientes->parentesco;?></td>
            <td></td>
        </tr>    
   <?php endforeach;?>  
   		<tr>
        	<td colspan="3">       
    <div class="clear"></div>     
     <?php if (isset($this->paginacion)) echo $this->paginacion; ?>                                      
     		</td>
        </tr>    
    </tbody>
</table>
<?php else: ?>
	<div class='alert alert-info'>
		<strong>No hay parientes asociados.</strong>
	</div>
<?php endif; ?>