<!DOCTYPE html>
<html lang="en">
     <head>
     <title>titulo</title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
<!--*******************************ETIQUETAS DE LA ANTIGUA PAGINA********************************-->
<meta name="country" content="COLOMBIA">
<meta name="language" content="spanish">
<meta name="coverage" content="Worldwide">
<meta name="creation_date" content="MAY 2009">
<META NAME="RATING" CONTENT="General">
<META NAME="ROBOTS" CONTENT="index, default">
<meta name="distribution" content="global">
<meta name="revisit-after" content="2 days">    
<!--********************************************************************************************-->     

     
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >

     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/funciones.js"></script>
     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->

    <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/lightbox.css" />
    <script src="<?php echo BASE_URL; ?>public/js/lightbox-2.6.min.js" type="text/javascript"></script>

    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
      <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">


    <![endif]-->
    <script src="<?php echo BASE_URL; ?>views/layout/twb/js/ContadorClics.js"></script>
    
<!--*******************************CODIGO DE GOOGLE ANALYTICS NUEVO********************************-->
   
      <script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-64286996-1', 'auto');
		  ga('send', 'pageview');
	 </script>
    
<!--********************************************************************************************-->     
   
    
 </head>
 <body class="page1" id="top" style="background-color:#3e3e9e" >
 <div class="main_color">
								    
<!--==============================HEADER=================================--> 
<div style="width:100%;background-color:#3e3e9e; padding-top:5px; padding-bottom:5px; ">
<div class="container_12" style="width:100%;background-color:#3e3e9e">

  <!--
  <div class="grid_07" style="padding-left:10px;margin-bottom:5px;">
  <a href="<?php echo BASE_URL; ?>micuenta/micuenta" title="Mi Perfil">  
    <img src="<?php echo BASE_URL?>public/img/usuariosinfoto.png" border="0"  style="width:100%" class="img-circle" />
  </a>  
  </div>-->

  <div class="grid_03" style="margin-bottom:5px;">
      <a href="<?php echo BASE_URL; ?>principal">
        <img src="<?php echo BASE_URL; ?>public/img/logo-SCIOCCO.png" alt="SCIOCCO">
      </a>
  </div>

  <?php if (Session::Get('modulo') == "prin"){ ?>

  <div class="grid_06" style="margin-bottom:2px;">

    <div class="grid_04" style="margin-top:2px;margin-bottom:2px;">
      <a href="<?php echo BASE_URL; ?>login/login" style="color:#FFF; font-weight:bold" title="Iniciar Sesi&oacute;n">
      <img src="<?php echo BASE_URL; ?>public/img/iniciar_sesion.png">
      </a>
    </div>

    <div class="grid_04" style="margin-top:2px;margin-bottom:2px;">
      <a href="<?php echo BASE_URL; ?>login/cerrar" style="color:#FFF; font-weight:bold" title="Cerrar Sesi&oacute;n">
      <img src="<?php echo BASE_URL; ?>public/img/cerrar_sesion.png">
      </a>
    </div>
  
    <div class="grid_04" style="margin-top:2px;margin-bottom:2px;">
      <a href="<?php echo BASE_URL; ?>micuenta/micuenta" style="color:#FFF; font-weight:bold" title="Mi Perfil">
      <img src="<?php echo BASE_URL; ?>public/img/mi_cuenta.png">
      </a> 
    </div>
    
    
    	
    <div class="grid_09" style="margin-top:2px;margin-bottom:2px;">
      <a class="btn1" href="<?php echo BASE_URL; ?>micuenta/ListadoCarrito" style="color:#06C; font-weight:bold; background:#FFF;width:102px;" title="Comprar Más">
      <img src="<?php echo BASE_URL; ?>public/img/icono-carrito.png"> Carrito <span>()</span>
      </a>
  	</div>
    
    <div class="grid_09" style="margin-top:2px;margin-bottom:2px;">
      <a class="btn1" href="<?php echo BASE_URL; ?>compras" style="color:#06C; font-weight:bold; background:#FFF;width:102px;" title="Comprar Más">
      <img src="<?php echo BASE_URL; ?>public/img/comprar_mas.png"> Comprar Más <span></span>
      </a>
  	</div>     
	</div>  

  <!--
  <div class="grid_08" style="padding-left:10px;">
  <a href="<?php echo BASE_URL; ?>micuenta/micuenta" title="Mi Perfil">    
    <img src="<?php echo BASE_URL?>public/img/usuariosinfoto.png" border="0"   style="width:100%" class="img-circle" />
  </a>  
  </div>--> 

    <?php }elseif (Session::Get('modulo') =="admin"){ ?>
      <?php if (Session::Get('autenticado_adminsciocco') == true ){ ?>
        <div class="grid_04" style="margin-top:2px;margin-bottom:2px;">
          <a href="<?php echo BASE_URL; ?>login/cerrar" style="color:#FFF; font-weight:bold" title="Cerrar Sesi&oacute;n">
          <img src="<?php echo BASE_URL; ?>public/img/cerrar_sesion.png">
          </a>
        </div>
      <?php } ?> 
    <?php } ?>     


</div>

<br>

</div>          

<!--==============================MENU DE NAVEGACION=================================--> 
<style type="text/css">
	.menu_nav{width:345px;}
    @media only screen and (min-width: 768px) and (max-width: 995px) {
		.menu_nav{width:100px;}
	}
    @media only screen and (max-width: 767px) {
		.menu_nav{width:50px;}
	}
	@media only screen and (min-width: 480px) and (max-width: 767px) {
		.menu_nav{width:50px;}
	}
</style>
<div class="menu_block ">
  <nav class="horizontal-nav full-width horizontalNav-notprocessed">
    </nav>
</div>


<!--==============================CONTENIDO=================================--> 
  <div class="container_12" class="main_color">
    <div class="grid_12" align="center" class="main_color">
      <div style="min-height:490px;" class="main_color">
        <?php include $this->_contenido; ?>
      </div>
    </div>                
  </div>
</div> 

<!--==============================FOOTER=================================-->

<footer>   
  <div class="container_12" >   
    <div class="grid_12" align="right">
		  <a target="_blank" href="" style="text-align: right;">
        Desarrollado por <font Title="Desarrollado por DEEPCODE" 
        alt="Desarrollado por DEEPCODE"  >DEEPCODE</font>
      <!-- <img style="margin-top: 4px;" border="0" 
      src="<?php echo BASE_URL; ?>public/img/logo-deepcode.png"  />-->
      </a>	
    </div> 
  </div>  
</footer>

  
        <script type="text/javascript">
            var _ruta_ = '<?php echo BASE_URL; ?>';
        </script>

        <?php if (isset($this->_layoutParams['js_plugin']) && count($this->_layoutParams['js_plugin'])): ?>
            <?php for ($i = 0; $i < count($this->_layoutParams['js_plugin']); $i++): ?>

                <script language="JavaScript" src="<?php echo $this->_layoutParams['js_plugin'][$i] ?>" type="text/javascript"></script>

            <?php endfor; ?>
        <?php endif; ?>


        <?php if (isset($this->_layoutParams['js']) && count($this->_layoutParams['js'])): ?>
            <?php for ($i = 0; $i < count($this->_layoutParams['js']); $i++): ?>

                <script src="<?php echo $this->_layoutParams['js'][$i] ?>" type="text/javascript"></script>

            <?php endfor; ?>
        <?php endif; ?>
          
</body>
</html>