<div class="content">
	<div class="container_12" >
		<br>
    	<div class="grid_12">
	    		<a style="text-align:left;" title="PANEL" href="<?php echo BASE_URL; ?>panel"><img src="<?php echo BASE_URL; ?>public/img/prev.png" align="left"></a>
    	</div>	
   		
   		<br>
		<table align="center" >
			<tr style="heigth:33%;">
				<td class="text-center" style="text-align:center;width:50%;padding:20px;">
					<a style="text-align:center;" href="<?php echo BASE_URL; ?>items/categorias"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/empresa.png" align="center"></a><br>
					<span >CATEGORIAS</span>
				</td>
				<td class="text-center" style="text-align:center;width:50%;padding:20px;">
					<a style="text-align:center;" href="<?php echo BASE_URL; ?>items/subcategorias"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/empresa.png" align="center"></a><br>
					<span >SUBCATEGORIAS</span>
				</td>				
			</tr>
			<tr style="heigth:33%;">
				<td class="text-center" style="text-align:center;width:50%;padding:20px;">
					<a style="align:center;" href="<?php echo BASE_URL; ?>items/tallas"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/redes_sociales.png" align="center"></a><br>
					<span>TALLAS</span>
				</td>
				<td class="text-center" style="text-align:center;width:50%;padding:20px;">
					<a style="align:center;" href="<?php echo BASE_URL; ?>items/productos"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/redes_sociales.png" align="center"></a><br>
					<span>PRODUCTOS</span>
				</td>	
			</tr>
		</table>	
	</div>
</div>