<!DOCTYPE html>
<html lang="en">
     <head>
     <title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     <meta charset="utf-8">
     <meta name = "format-detection" content = "telephone=no" />
     <link rel="icon" href="images/favicon.ico">
     <link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />
     
     <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css">

     
             
     <script src="<?php echo BASE_URL; ?>public/js/jquery.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery_migrate.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/script.js"></script> 
     <script src="<?php echo BASE_URL; ?>public/js/superfish.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.ui.totop.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.equalheights.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobilemenu.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery.easing.1.3.js"></script>
     <script src="<?php echo BASE_URL; ?>public/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
     <script src="<?php echo BASE_URL; ?>public/js/CalendarioEspanol.js" type="text/javascript"></script>
     
     <!--[if (gt IE 9)|!(IE)]><!-->
     <script src="<?php echo BASE_URL; ?>public/js/jquery.mobile.customized.min.js"></script>
     <!--<![endif]-->

    <!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
         </a>
      </div>
      <![endif]-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <link rel="stylesheet" media="screen" href="css/ie.css">


    <![endif]-->
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
     <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css">

<script src="<?php echo BASE_URL; ?>views/items/js/foto_producto.js"></script>
<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
<script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
<script src="<?php echo BASE_URL; ?>public/js/funciones.js"></script> 

<style type="text/css">
            .titulo1{
            font-size:20px;
            color:#a0a2a2;
            font-weight:900;
            }

            .titulo2{
            font-size:14px;
            color:#a0a2a2;
            font-weight:900;
            }

            .form_imput{
            width:240px;
            height:32px;
            border:1px solid #cdcfd2;
            }

            .form_imput::-moz-placeholder{
            color:#777;opacity:
            }

            .form_imput:focus{
            border-color:#0B6EC7;
            -webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
            box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
            }
            
        </style>

     </head>
     
<body class="main_color" align="center">
    <div >
        <div align="left">
            <br />
            <font style="font-size:18px;font-weight:bold">IMAGENES PRODUCTOS</font>
            <hr style="color:#999" />
            <a href="<?php echo BASE_URL; ?>items/subir_foto/<?php echo $this->id?>" class="btn5 ventanafoto"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> NUEVA FOTO</a>                
            <br/>
        </div>
    </div>    
    <br>
    <?php $contar = 0;?>
    <?php if (isset($this->imagenes) && count($this->imagenes)) : ?>   
        <table cellpadding="3" cellspacing="0" width="80%" border="0" style="margin-left:10%;">
            <tr>
            <?php foreach($this->imagenes as $imagenes):?>
            <?php $contar = $contar+1;?>                
                    <td><?php if (file_exists("views/items/fotos/".$imagenes->archivo.".jpg")): ?>
                        <a  href='<?php echo BASE_URL . "views/items/fotos/".$imagenes->archivo ?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' data-lightbox='<?php echo $imagenes->archivo?>' >
             
                            <img src='<?php echo BASE_URL . "views/items/fotos/".$imagenes->archivo?>.jpg?nocache= <?php echo date("Y-m-d H:i:s")?>' style="border:1px solid #CCC;-webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);" />     
                         </a>
                         <br>
                         <a href="javascript:borrar_foto(<?php echo $imagenes->id;?>)" ><img src="<?php echo BASE_URL; ?>public/img/eliminar_negro.png" style="vertical-align:middle"/> ELIMINAR</a>
                         <br>
                        <?php else: ?>
            
                            <img src='<?php echo BASE_URL; ?>public/img/img_nodis_micuenta' style="border:1px solid #CCC;-webkit-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.75);"/>
                
                            <?php endif; ?></td>
            <?php if ($contar == 3){?>
            <br><br><tr>
            <?php $contar = 0;
            }?>
            <?php endforeach;?>
            </tr>
        </table>

    <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay productos creados.</strong>
                </div>
            <?php endif; ?>

 </body>
