<?php if (isset($this->producto) && count($this->producto)) : ?>   
                    <table class="table" style="width:100%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:10%;"><b>CATEGORIA</b></td>
                            <td style="width:15%;"><b>SUBCATEGORIA</b></td>
                            <td style="width:15%;"><b>PRODUCTO</b></td>
                            <td style="width:10%;"><b>PRECIO</b></td>
                            <td style="width:10%;"><b>ESTADO</b></td>
                            <td style="width:30%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->producto as $producto):?>
                            <tr>
                                <td><?php echo $producto->categoria;?></td>
                                <td><?php echo $producto->subcategoria;?></td>
                                <td><?php echo $producto->referencia;?></td>
                                <td><?php echo $producto->precio;?></td>
                                <td><?php if($producto->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>items/editar_producto/<?php echo $producto->id?>" class="btn2 ventanaproducto"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>

                                    <a href="<?php echo BASE_URL; ?>items/listado_img_producto/<?php echo $producto->id?>" class="btn3 ventanaimagenes"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> IMAGENES</a>

                                    <a href="javascript:borrar_producto(<?php echo $producto->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="6">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay productos creados.</strong>
                </div>
            <?php endif; ?>