<?php if (isset($this->categoria) && count($this->categoria)) : ?>   
                    <table class="table" style="width:60%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:30%;"><b>CATEGORIA</b></td>
                            <td style="width:15%;"><b>ESTADO</b></td>
                            <td style="width:40%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->categoria as $categoria):?>
                            <tr>
                                <td><?php echo $categoria->nombre_cat;?></td>
                                <td><?php if($categoria->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>items/editar_categoria/<?php echo $categoria->id?>" class="btn2 ventanacategoria"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>

                                    <a href="javascript:borrar_categoria(<?php echo $categoria->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="3">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay categorias creadas.</strong>
                </div>
            <?php endif; ?>