<?php if (isset($this->subcategoria) && count($this->subcategoria)) : ?>   
                    <table class="table" style="width:80%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:30%;"><b>CATEGORIA</b></td>
                            <td style="width:30%;"><b>SUBCATEGORIA</b></td>
                            <td style="width:15%;"><b>ESTADO</b></td>
                            <td style="width:40%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->subcategoria as $subcategoria):?>
                            <tr>
                                <td><?php echo $subcategoria->nombre_cat;?></td>
                                <td><?php echo $subcategoria->nombre_subcategoria;?></td>
                                <td><?php if($subcategoria->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>items/editar_subcategoria/<?php echo $subcategoria->id?>" class="btn2 ventanasubcategoria"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>

                                    <a href="javascript:borrar_subcategoria(<?php echo $subcategoria->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="4">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay subcategorias creadas.</strong>
                </div>
            <?php endif; ?>