<div class="container_12" >
	<table align="center">
		<tr style="heigth:33%;">
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a style="text-align:center;" href="<?php echo BASE_URL; ?>empresa"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/empresa.png" ></a><br>
				<span >EMPRESA</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>terminos"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/terminos.png" ></a><br>
				<span>TERMINOS</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a style="align:center;" href="<?php echo BASE_URL; ?>configuracion"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/configuracion.png" ></a><br>
				<span>CONFIGURACION</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>recursos"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/recursos.png" ></a><br>
				<span>RECURSOS</span>
			</td>	
		</tr>
		<tr style="heigth:33%;">
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>usuarios"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/usuarios.png" ></a><br>
				<span>USUARIOS</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>clientes"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/cliente.png" ></a><br>
				<span>CLIENTES</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>proveedores"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/proveedor.png" ></a><br>
				<span>PROVEEDORES</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>marcas"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/empresa.png" ></a><br>
				<span>MARCAS</span>
			</td>
		</tr>
		<tr style="heigth:33%;">
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>novedades"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/items.png" ></a><br>
				<span>NOVEDADES</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>items"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/items.png" ></a><br>
				<span>ITEMS</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>compras"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/compras.png" ></a><br>
				<span>COMPRAS</span>
			</td>
			<td class="text-center" style="text-align:center;width:25%;padding:20px;">
				<a href="<?php echo BASE_URL; ?>reportes"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/reportes.png" ></a><br>
				<span>REPORTES</span>
			</td>
		</tr>
	</table>	
</div>