	<head>
    	<title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     	<meta charset="utf-8">
     	<meta name = "format-detection" content = "telephone=no" />
     	<link rel="icon" href="images/favicon.ico">
     	<link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />

        <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
<script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
     
     	<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css"> 

		<style type="text/css">
			.titulo1{
			font-size:20px;
			color:#a0a2a2;
			font-weight:900;
			}

			.titulo2{
			font-size:14px;
			color:#a0a2a2;
			font-weight:900;
			}

			.form_imput{
			width:240px;
			height:32px;
			border:1px solid #cdcfd2;
			}

			.form_imput::-moz-placeholder{
			color:#777;opacity:
			}

			.form_imput:focus{
			border-color:#0B6EC7;
			-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
			box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
			}
			
		</style>
	</head>
     
<div class="content">
    <div class="container_12">
    	<br>
    	<div class="grid_12">
    		<a style="text-align:left;" title="PANEL" href="<?php echo BASE_URL; ?>panel"><img src="<?php echo BASE_URL; ?>public/img/prev.png" align="left"></a>
    	</div>		

        <div >
            <div align="left">
                <br />
                <font style="font-size:18px;font-weight:bold">MARCAS</font>
                <hr style="color:#999" /> <a href="<?php echo BASE_URL; ?>marcas/crear_marca" class="btn5 ">
                <img src="<?php echo BASE_URL; ?>public/img/crear.png" style="vertical-align:middle"/> 
                Crear</a> 
                <br/>
            </div>
        </div>

        <div class="grid_12">
            <div id="lista_registros">     
                <?php if (isset($this->marca) && count($this->marca)) : ?>   
                    <table class="table" style="width:100%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:20%;"><b>PROVEEDOR</b></td>
                            <td style="width:15%;"><b>MARCA</b></td>
                            <td style="width:15%;"><b>ESTADO</b></td>
                            <td style="width:40%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->marca as $marca):?>
                            <tr>
                                <td><?php echo $marca->razon_social;?></td>
                                <td><?php echo $marca->marca;?></td>
                                <td><?php if($marca->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>marcas/editar_marca/<?php echo $marca->id?>" class="btn2 ventanamarca"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>

                                    <?php if ($marca->archivo == "") { ?>

                                        <a href="<?php echo BASE_URL; ?>marcas/subir_foto/<?php echo $marca->id?>" class="btn3 ventanafoto"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/>SUBIR FOTO</a>

                                    <?php } 

                                    if ($marca->archivo <> ""){ ?>

                                        <a href="javascript:borrar_foto(<?php echo $marca->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> BORRAR FOTO</a>
                                        
                                    <?php } ?>

                                    <a href="<?php echo BASE_URL; ?>marcas/ver_marca/<?php echo $marca->id?>" class="btn3 ventanaver"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> VER</a>


                                    <a href="javascript:borrar_marca(<?php echo $marca->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="4">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay marcas creadas.</strong>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
</div>    