<?php if (isset($this->marca) && count($this->marca)) : ?>   
                    <table class="table" style="width:100%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:20%;"><b>PROVEEDOR</b></td>
                            <td style="width:15%;"><b>MARCA</b></td>
                            <td style="width:15%;"><b>ESTADO</b></td>
                            <td style="width:40%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->marca as $marca):?>
                            <tr>
                                <td><?php echo $marca->razon_social;?></td>
                                <td><?php echo $marca->marca;?></td>
                                <td><?php if($marca->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>marcas/editar_marca/<?php echo $marca->id?>" class="btn2 ventanamarca"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>

                                    <?php if ($marca->archivo == "") { ?>

                                        <a href="<?php echo BASE_URL; ?>marcas/subir_foto/<?php echo $marca->id?>" class="btn3 ventanafoto"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/>SUBIR FOTO</a>

                                    <?php } 

                                    if ($marca->archivo <> ""){ ?>

                                        <a href="javascript:borrar_foto(<?php echo $marca->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> BORRAR FOTO</a>
                                        
                                    <?php } ?>

                                    <a href="<?php echo BASE_URL; ?>marcas/ver_marca/<?php echo $marca->id?>" class="btn3 ventanaver"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> VER</a>


                                    <a href="javascript:borrar_marca(<?php echo $marca->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="4">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay marcas creadas.</strong>
                </div>
            <?php endif; ?>