<div class="content">
	<div class="container_12" >
		<br>
    	<div class="grid_12">
	    		<a style="text-align:left;" title="PANEL" href="<?php echo BASE_URL; ?>panel"><img src="<?php echo BASE_URL; ?>public/img/prev.png" align="left"></a>
	    		
	    		
	    	
    	</div>	
   		
   		<br>
		<table align="center" >
			<tr style="heigth:33%;">
				<td class="text-center" style="text-align:center;width:33%;padding:20px;">
					<a style="text-align:center;" href="<?php echo BASE_URL; ?>configuracion/roles"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/empresa.png" align="center"></a><br>
					<span >ROLES</span>
				</td>
				<td class="text-center" style="text-align:center;width:33%;padding:20px;">
					<a style="align:center;" href="<?php echo BASE_URL; ?>configuracion/t_novedades"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/redes_sociales.png" align="center"></a><br>
					<span>TIPO NOVEDAD</span>
				</td>
				<td class="text-center" style="text-align:center;width:33%;padding:20px;">
					<a style="align:center;" href="<?php echo BASE_URL; ?>configuracion/t_documentos"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/redes_sociales.png" align="center"></a><br>
					<span>TIPO DOCUMENTO</span>
				</td>
				
			</tr>
			<tr style="heigth:33%;">
				
			</tr>
		</table>	
	</div>
</div>