<?php if (isset($this->rol) && count($this->rol)) : ?>   
                    <table class="table" style="width:60%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:60%;"><b>ROL</b></td>
                            <td style="width:35%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->rol as $rol):?>
                            <tr>
                                <td><?php echo $rol->rol;?></td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>configuracion/editar_rol/<?php echo $rol->id?>" class="btn2 ventanarol"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                                    <a href="javascript:borrar_rol(<?php echo $rol->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="3">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay roles creados.</strong>
                </div>
            <?php endif; ?>