<?php if (isset($this->tdocumento) && count($this->tdocumento)) : ?>   
                    <table class="table" style="width:60%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:60%;"><b>TIPO DOCUMENTO</b></td>
                            <td style="width:35%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->tdocumento as $tdocumento):?>
                            <tr>
                                <td><?php echo $tdocumento->tipo_doc;?></td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>configuracion/editar_t_documento/<?php echo $tdocumento->id?>" class="btn2 ventanat_documento"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                                    <a href="javascript:borrar_t_documento(<?php echo $tdocumento->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="3">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay tipos de documentos creados.</strong>
                </div>
            <?php endif; ?>