<?php if (isset($this->t_nov) && count($this->t_nov)) : ?>   
    <table class="table" style="width:90%; font-size:12px;">
        <thead>
            <tr>
                <td style="width:30%;"><b>TIPO DOCUMENTO</b></td>
                <td style="width:30%;"><b>ESTADO</b></td>
                <td style="width:25%;"><b>ACCIONES</b></td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->t_nov as $t_nov):?>
                <tr>
                    <td><?php echo $t_nov->nombre;?></td>
                    <td><?php if($t_nov->estado == 1){
                            echo "Activo";
                        }else{
                            echo "Inactivo";
                        }?> 
                    </td>
                    <td>
                        <a href="<?php echo BASE_URL; ?>configuracion/editar_t_novedad/<?php echo $t_nov->id?>" class="btn2 ventanat_novedad"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                        <a href="javascript:borrar_t_novedad(<?php echo $t_nov->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr>
                <td colspan="3">
                    <div class="clear"></div>
                    <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php else: ?>
    <div class='alert alert-info'>
        <strong>No hay tipos de novedades creados.</strong>
    </div>
<?php endif; ?>