	<head>
    	<title><?php if (isset($this->titulo)) echo $this->titulo; ?></title>
     	<meta charset="utf-8">
     	<meta name = "format-detection" content = "telephone=no" />
     	<link rel="icon" href="images/favicon.ico">
     	<link rel = "shortcut icon" type = "image/png" href = "<?php echo BASE_URL; ?>public/img/favicon.ico" />

        <link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/jquery.fancybox.css" />
<script src="<?php echo BASE_URL; ?>public/js/jquery.fancybox.js"></script>
     
     	<link rel="stylesheet" href="<?php echo BASE_URL; ?>public/css/style.css">
     	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/EstilosPagina.css" >
        <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>public/css/custom-theme/jquery-ui-1.10.3.custom.css"> 

		<style type="text/css">
			.titulo1{
			font-size:20px;
			color:#a0a2a2;
			font-weight:900;
			}

			.titulo2{
			font-size:14px;
			color:#a0a2a2;
			font-weight:900;
			}

			.form_imput{
			width:240px;
			height:32px;
			border:1px solid #cdcfd2;
			}

			.form_imput::-moz-placeholder{
			color:#777;opacity:
			}

			.form_imput:focus{
			border-color:#0B6EC7;
			-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7;
			box-shadow:inset 0 1px 1px rgba(0,0,0,0.075),0 0 6px #0B6EC7
			}
			
		</style>
	</head>
     
<div class="content">
    <div class="container_12">
    	<br>
    	<div class="grid_12">
    		<a style="text-align:left;" title="PANEL" href="<?php echo BASE_URL; ?>panel"><img src="<?php echo BASE_URL; ?>public/img/prev.png" align="left"></a>
	    		
    		<a style="text-align:rigth;margin-left:80%" title="PANEL CONFIGURACIÍON" href="<?php echo BASE_URL; ?>configuracion"><img src="<?php echo BASE_URL; ?>public/img/menu_panel_adm/configuracion.png" align="rigth"></a>	
    	</div>		

        <div >
            <div align="left">
                <br />
                <font style="font-size:18px;font-weight:bold">TIPOS DE NOVEDADES</font>
                <hr style="color:#999" /> <a href="<?php echo BASE_URL; ?>configuracion/nuevo_t_novedad" class="btn5 ">
                <img src="<?php echo BASE_URL; ?>public/img/crear.png" style="vertical-align:middle"/> 
                Crear</a> 
                <br/>
            </div>
        </div>

        <div class="grid_12">
            <div id="lista_registros">     
                <?php if (isset($this->t_nov) && count($this->t_nov)) : ?>   
                    <table class="table" style="width:90%; font-size:12px;">
                    <thead>
                        <tr>
                            <td style="width:30%;"><b>TIPO DOCUMENTO</b></td>
                            <td style="width:30%;"><b>ESTADO</b></td>
                            <td style="width:25%;"><b>ACCIONES</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->t_nov as $t_nov):?>
                            <tr>
                                <td><?php echo $t_nov->nombre;?></td>
                                <td><?php if($t_nov->estado == 1){
                                        echo "Activo";
                                    }else{
                                        echo "Inactivo";
                                    }?> 
                                </td>
                                <td>
                                    <a href="<?php echo BASE_URL; ?>configuracion/editar_t_novedad/<?php echo $t_nov->id?>" class="btn2 ventanat_novedad"><img src="<?php echo BASE_URL; ?>public/img/editar.png" style="vertical-align:middle"/> Editar</a>
                                    <a href="javascript:borrar_t_novedad(<?php echo $t_nov->id;?>)" class="btn4"><img src="<?php echo BASE_URL; ?>public/img/remover_todos.png" style="vertical-align:middle"/> Eliminar</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        <tr>
                            <td colspan="3">
                                <div class="clear"></div>
                                <?php if (isset($this->paginacion)) echo $this->paginacion; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            <?php else: ?>
                <div class='alert alert-info'>
                    <strong>No hay tipos de novedades creados.</strong>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
</div>    